import { useState } from "react";

const ROOMS_DATA = [
  { id: "L", name: "Laachi Queen", cat: "Desi", color: "#ff1493", viewers: "2.1k" },
  { id: "J", name: "Jalalpur Doll", cat: "Punjabi", color: "#8a2be2", viewers: "1.8k" },
  { id: "G", name: "Gujrat Rose", cat: "New", color: "#00bfff", viewers: "890" },
  { id: "P", name: "Pari", cat: "Trending", color: "#ff8c00", viewers: "3.2k" },
];

const GIFTS_DATA = [
  { i: "🌹", n: "Rose", p: 100 }, { i: "🧸", n: "Teddy", p: 500 },
  { i: "💍", n: "Ring", p: 1000 }, { i: "🏎️", n: "Car", p: 2000 },
  { i: "👑", n: "Crown", p: 3000 }, { i: "🚀", n: "Rocket", p: 5000 },
  { i: "🦁", n: "Lion", p: 10000 }, { i: "🏰", n: "Castle", p: 20000 },
  { i: "🌌", n: "Universe", p: 50000 },
];

export default function App(){
  const [sel,setSel]=useState<any>(null);
  const [tab,setTab]=useState("home");
  const [rooms,setRooms]=useState(()=>{
    const s=localStorage.getItem("laachi_rooms_v2");
    return s?JSON.parse(s):ROOMS_DATA;
  });
  const [user,setUser]=useState<any>(()=>{ const s=localStorage.getItem("laachi_user"); return s?JSON.parse(s):null });
  const [name,setName]=useState(""); const [pass,setPass]=useState(""); const [showP,setShowP]=useState(false);
  const [showCreate,setShowCreate]=useState(false); const [newRoomName,setNewRoomName]=useState(""); const [newRoomCat,setNewRoomCat]=useState("Desi");
  const [seats,setSeats]=useState<any[]>([]); const [muted,setMuted]=useState(false);
  const [msg,setMsg]=useState(""); const [chats,setChats]=useState<string[]>(["Welcome to LaachiLive! 🎉"]);
  const [coins,setCoins]=useState(5000); const [diamonds,setDiamonds]=useState(10000);
  const [showGift,setShowGift]=useState(false); const [bigGift,setBigGift]=useState<any>(null);
  const [myId]=useState(()=>Math.floor(Math.random()*90000)+10000);

  const saveRooms=(nr:any[])=>{ setRooms(nr); localStorage.setItem("laachi_rooms_v2", JSON.stringify(nr)); };
  const handleCreate=()=>{ if(!newRoomName) return alert("Room ka naam likho!"); const colors=["#ff1493","#8a2be2","#00bfff","#ff8c00","#00ff7f"]; const r={ id: newRoomName[0].toUpperCase(), name: newRoomName, cat: newRoomCat, color: colors[Math.floor(Math.random()*5)], viewers:"1" }; saveRooms([r,...rooms]); setNewRoomName(""); setShowCreate(false); setTab("home"); };
  const openRoom=(r:any)=>{ setSel(r); setSeats(Array.from({length:25},(_,i)=>i===0?{name:user.name,isHost:true}:null)); setChats([`Welcome to ${r.name}! 🎉`,`${user.name} joined as Host 👑`]); };
  const doSignUp=()=>{ if(!name||!pass) return alert("Naam likho"); localStorage.setItem(`user_${name}`,pass); localStorage.setItem("laachi_user",JSON.stringify({name})); setUser({name}); };
  const doLogin=()=>{ if(!name||!pass) return alert("Naam likho"); const sp=localStorage.getItem(`user_${name}`); if(!sp) return alert("Naam nahi mila"); if(sp!==pass) return alert("Password galat"); localStorage.setItem("laachi_user",JSON.stringify({name})); setUser({name}); };
  const googleLogin=()=>{ const g="Umais Google"; localStorage.setItem("laachi_user",JSON.stringify({name:g})); setUser({name:g}); };
  const logout=()=>{ localStorage.removeItem("laachi_user"); setUser(null); setSel(null); setTab("home"); };
  const sit=(idx:number)=>{ if(seats[idx]) return; if(seats.some((s:any)=>s?.name===user.name)) return alert("Aap pehle se seat par ho!"); const ns=[...seats]; ns[idx]={name:user.name,isHost:false}; setSeats(ns); setChats(p=>[...p,`${user.name} sat on seat ${idx+1} 🎤`]); };
  const leave=(idx:number)=>{ if(idx===0) return alert("Host seat nahi chor sakta!"); if(seats[idx]?.name!==user.name) return; const ns=[...seats]; ns[idx]=null; setSeats(ns); };
  const sendChat=()=>{ if(!msg) return; setChats([...chats,`${user.name}: ${msg}`]); setMsg(""); };
  const sendGift=(g:any)=>{ if(coins<g.p) return alert(`Coins kam! Aapke pas ${coins} hain, ${g.p} chahiye`); setCoins(c=>c-g.p); setDiamonds(d=>d+Math.floor(g.p/2)); setChats(p=>[...p,`🎁 ${user.name} ne ${g.i} ${g.n} bheja - ${g.p} coins!`]); setBigGift(g); setShowGift(false); setTimeout(()=>setBigGift(null),2500); };

  if(sel){
    return(<div style={{background:"linear-gradient(180deg,#1a0033 0%,#000 100%)",color:"#fff",minHeight:"100vh",display:"flex",flexDirection:"column",position:"relative"}}>
      {bigGift&&<div style={{position:"fixed",inset:0,zIndex:200,background:"rgba(0,0,0,0.8)",display:"flex",alignItems:"center",justifyContent:"center",flexDirection:"column"}}><div style={{fontSize:110, animation:"pulse 0.6s infinite"}}>{bigGift.i}</div><div style={{fontSize:22,fontWeight:"bold",color:"#ff1493",marginTop:10}}>{bigGift.n} Sent!</div><div style={{fontSize:13,color:"gold"}}>-{bigGift.p} Coins</div></div>}
      <div style={{display:"flex",justifyContent:"space-between",padding:"10px 15px",alignItems:"center",background:"rgba(0,0,0,0.5)"}}><button onClick={()=>setSel(null)} style={{background:"#ff1493",color:"#fff",padding:"6px 15px",borderRadius:20,border:"none"}}>← Back</button><div style={{textAlign:"center"}}><b style={{fontSize:14}}>{sel.name}</b><div style={{fontSize:10,color:"#aaa"}}>ID: 107{myId}</div></div><span style={{background:"#222",padding:"5px 10px",borderRadius:15,fontSize:11}}>🪙 {coins}</span></div>
      <div style={{padding:10,display:"grid",gridTemplateColumns:"repeat(5, 1fr)",gap:8,flex:1,overflowY:"auto"}}>{seats.map((s:any,i:number)=>(<div key={i} onClick={()=>s?leave(i):sit(i)} style={{background:s?s.isHost?"rgba(255,215,0,0.2)":"rgba(255,20,147,0.2)":"rgba(255,255,255,0.05)",border:s?"1px solid #ff1493":"1px dashed #333",borderRadius:12,padding:"8px 3px",textAlign:"center"}}><div style={{width:38,height:38,background:s?s.isHost?"gold":"#ff1493":"#222",borderRadius:20,margin:"0 auto",display:"flex",alignItems:"center",justifyContent:"center",fontSize:15,fontWeight:"bold",color:s?.isHost?"#000":"#fff"}}>{s?s.name[0].toUpperCase():"+"}</div><div style={{fontSize:9,marginTop:4,overflow:"hidden",whiteSpace:"nowrap"}}>{s?s.name:`Seat ${i+1}`}</div><div style={{fontSize:8,color:s?s.isHost?"gold":"#00ff7f":"#666"}}>{s?s.isHost?"👑 Host":"🎤 Live":"Empty"}</div></div>))}</div>
      <div style={{background:"rgba(0,0,0,0.6)",height:85,overflowY:"auto",padding:"8px 12px",fontSize:11}}>{chats.map((c,i)=><div key={i} style={{marginBottom:3,color:c.includes("🎁")?"#ff69b4":c.includes("Welcome")?"gold":"#ccc"}}>{c}</div>)}</div>
      {showGift&&<div style={{position:"absolute",bottom:70,left:0,right:0,background:"#111",borderTop:"2px solid #ff1493",borderRadius:"20px 20px 0 0",padding:15,zIndex:50,maxHeight:"55%",overflowY:"auto"}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:12}}><b>🎁 Send Gift</b><span style={{fontSize:12,background:"#222",padding:"3px 10px",borderRadius:10}}>🪙 {coins}</span></div><div style={{display:"grid",gridTemplateColumns:"repeat(3, 1fr)",gap:10}}>{GIFTS_DATA.map((g:any)=>(<div key={g.n} onClick={()=>sendGift(g)} style={{background:"#1a1a1a",border:"1px solid #333",borderRadius:12,padding:10,textAlign:"center"}}><div style={{fontSize:30}}>{g.i}</div><div style={{fontSize:11,marginTop:4}}>{g.n}</div><div style={{fontSize:10,color:"gold"}}>🪙 {g.p}</div></div>))}</div><button onClick={()=>setShowGift(false)} style={{width:"100%",marginTop:12,background:"#222",color:"#fff",border:"1px solid #333",padding:10,borderRadius:10}}>Close</button></div>}
      <div style={{background:"#0a0a0a",borderTop:"1px solid #222",padding:10}}><div style={{display:"flex",gap:6,marginBottom:10,overflowX:"auto"}}><div onClick={()=>setShowGift(!showGift)} style={{background:showGift?"#ff1493":"#1a1a1a",borderRadius:10,padding:"6px 12px",textAlign:"center",border:"1px solid #222",minWidth:45}}><div>🎁</div><div style={{fontSize:8}}>Gift</div></div>{[{icon:"💎",label:"Diamonds"},{icon:"🔒",label:"Lock"},{icon:"👢",label:"Kick"},{icon:"🎵",label:"Music"}].map((o:any)=>(<div key={o.label} style={{background:"#1a1a1a",borderRadius:10,padding:"6px 12px",textAlign:"center",border:"1px solid #222",minWidth:45}}><div>{o.icon}</div><div style={{fontSize:8}}>{o.label}</div></div>))}</div><div style={{display:"flex",gap:8,alignItems:"center"}}><button onClick={()=>setMuted(!muted)} style={{background:muted?"#ff4444":"#222",color:"#fff",border:"1px solid #333",padding:"10px 14px",borderRadius:25}}>{muted?"🔇":"🎤"}</button><input value={msg} onChange={e=>setMsg(e.target.value)} placeholder="Say..." style={{flex:1,background:"#1a1a1a",border:"1px solid #333",borderRadius:25,padding:"10px 15px",color:"#fff",fontSize:12}}/><button onClick={sendChat} style={{background:"#ff1493",color:"#fff",border:"none",padding:"10px 18px",borderRadius:25,fontWeight:"bold",fontSize:12}}>Send</button></div></div>
    </div>);
  }
  if(!user){ return(<div style={{background:"#000",color:"#fff",minHeight:"100vh",display:"flex",flexDirection:"column",alignItems:"center",padding:20}}><h1 style={{fontSize:32,fontWeight:900}}><span style={{color:"#ff1493"}}>Laachi</span>Live</h1><div style={{width:150,height:150,marginTop:15,borderRadius:75,background:"radial-gradient(circle, #ff1493 0%, #8a2be2 100%)",display:"flex",alignItems:"center",justifyContent:"center",fontSize:65}}>👩‍🦰</div><div style={{width:"100%",maxWidth:340,marginTop:18}}><div style={{background:"#111",borderRadius:18,padding:20,border:"1px solid #222"}}><h3 style={{textAlign:"center"}}>Login / Signup</h3><input value={name} onChange={e=>setName(e.target.value)} placeholder="Apna naam" style={{width:"100%",padding:12,borderRadius:10,border:"1px solid #333",background:"#1e1e1e",color:"#fff",boxSizing:"border-box",marginBottom:10}}/><div style={{position:"relative",marginBottom:15}}><input value={pass} onChange={e=>setPass(e.target.value)} type={showP?"text":"password"} placeholder="Password" style={{width:"100%",padding:"12px 40px 12px 12px",borderRadius:10,border:"1px solid #333",background:"#1e1e1e",color:"#fff",boxSizing:"border-box"}}/><span onClick={()=>setShowP(!showP)} style={{position:"absolute",right:12,top:11}}>{showP?"🙈":"👁️"}</span></div><button onClick={doLogin} style={{width:"100%",background:"#ff1493",color:"#fff",border:"none",padding:12,borderRadius:25,fontWeight:"bold"}}>Sign In</button><button onClick={doSignUp} style={{width:"100%",marginTop:10,background:"#222",color:"#fff",border:"1px solid #333",padding:12,borderRadius:25}}>New Account</button><button onClick={googleLogin} style={{width:"100%",marginTop:12,background:"#fff",color:"#000",border:"none",padding:11,borderRadius:25,fontWeight:"bold"}}>Continue with Google</button></div></div></div>); }
  return(<div style={{background:"#000",color:"#fff",minHeight:"100vh",paddingBottom:70}}>
    <div style={{display:"flex",justifyContent:"space-between",padding:"15px 20px",borderBottom:"1px solid #111",position:"sticky",top:0,background:"#000",zIndex:10}}><h2 style={{margin:0}}><span style={{color:"#ff1493"}}>Laachi</span>Live</h2><div style={{display:"flex",gap:8}}><span style={{background:"#1a1a1a",padding:"6px 12px",borderRadius:15,fontSize:11}}>🪙 {coins}</span><span style={{background:"#1a1a1a",padding:"6px 12px",borderRadius:15,fontSize:12}}>👤 {user.name}</span></div></div>
    {showCreate&&<div style={{position:"fixed",inset:0,background:"rgba(0,0,0,0.8)",zIndex:100,display:"flex",alignItems:"center",justifyContent:"center",padding:20}}><div style={{background:"#111",borderRadius:18,padding:20,width:"100%",maxWidth:320,border:"1px solid #333"}}><h3 style={{marginTop:0}}>Create Room</h3><input value={newRoomName} onChange={e=>setNewRoomName(e.target.value)} placeholder="Room Name - e.g. Gujrat Queen" style={{width:"100%",padding:12,borderRadius:10,border:"1px solid #333",background:"#1e1e1e",color:"#fff",marginBottom:12,boxSizing:"border-box"}}/><select value={newRoomCat} onChange={e=>setNewRoomCat(e.target.value)} style={{width:"100%",padding:12,borderRadius:10,border:"1px solid #333",background:"#1e1e1e",color:"#fff",marginBottom:15}}><option>Desi</option><option>Punjabi</option><option>New</option><option>Trending</option></select><div style={{display:"flex",gap:10}}><button onClick={()=>setShowCreate(false)} style={{flex:1,background:"#222",color:"#fff",border:"1px solid #333",padding:12,borderRadius:25}}>Cancel</button><button onClick={handleCreate} style={{flex:1,background:"#ff1493",color:"#fff",border:"none",padding:12,borderRadius:25,fontWeight:"bold"}}>Create</button></div></div></div>}
    {tab==="home"&&<div style={{padding:15}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:12}}><h3 style={{margin:0}}>🔥 Live Rooms ({rooms.length})</h3><button onClick={()=>setShowCreate(true)} style={{background:"#ff1493",color:"#fff",border:"none",padding:"6px 14px",borderRadius:20,fontSize:12,fontWeight:"bold"}}>+ Create Room</button></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}>{rooms.map((r:any)=>(<div key={r.name} onClick={()=>openRoom(r)} style={{background:"#111",borderRadius:15,overflow:"hidden",border:"1px solid #222"}}><div style={{background:r.color,height:110,display:"flex",alignItems:"center",justifyContent:"center",fontSize:35,position:"relative"}}>{r.id}<span style={{position:"absolute",top:6,right:6,background:"rgba(0,0,0,0.5)",fontSize:10,padding:"2px 6px",borderRadius:10}}>👁️ {r.viewers}</span></div><div style={{padding:10}}><b style={{fontSize:13}}>{r.name}</b><div style={{fontSize:11,color:"#aaa"}}>{r.cat}</div></div></div>))}</div></div>}
    {tab==="live"&&<div style={{padding:30,textAlign:"center"}}><h2>🎙️ Go Live</h2><p style={{color:"#666",fontSize:13}}>Apna room banao aur live jao</p><button onClick={()=>setShowCreate(true)} style={{background:"#ff1493",color:"#fff",border:"none",padding:"14px 30px",borderRadius:25,fontWeight:"bold",fontSize:14,marginTop:15}}>+ Create My Room</button></div>}
    {tab==="message"&&<div style={{padding:20}}><h3>💬 Messages</h3><div style={{background:"#111",borderRadius:12,padding:15,border:"1px solid #222",marginTop:10}}><div style={{color:"#aaa",fontSize:13}}>No new messages</div><div style={{color:"#666",fontSize:11,marginTop:5}}>Gifts aur room invites yahan ayenge</div></div></div>}
    {tab==="profile"&&<div><div style={{background:"linear-gradient(135deg,#ff1493,#8a2be2)",padding:25,borderRadius:"0 0 25px 25px"}}><div style={{display:"flex",gap:15,alignItems:"center"}}><div style={{width:80,height:80,background:"#fff",borderRadius:40,display:"flex",alignItems:"center",justifyContent:"center",fontSize:36,color:"#000",fontWeight:"bold"}}>{user.name[0].toUpperCase()}</div><div><h2 style={{margin:0,fontSize:20}}>{user.name} 👑</h2><div style={{fontSize:12,opacity:0.9}}>ID: 107{myId} | Level 1</div><div style={{fontSize:11,marginTop:4,background:"rgba(0,0,0,0.3)",padding:"3px 8px",borderRadius:10,display:"inline-block"}}>🔥 Pakistan</div></div></div><div style={{display:"flex",gap:10,marginTop:20}}><div style={{flex:1,background:"rgba(0,0,0,0.3)",borderRadius:12,padding:10,textAlign:"center"}}><div style={{fontSize:18,fontWeight:"bold"}}>💎 {diamonds.toLocaleString()}</div><div style={{fontSize:10}}>Diamonds</div></div><div style={{flex:1,background:"rgba(0,0,0,0.3)",borderRadius:12,padding:10,textAlign:"center"}}><div style={{fontSize:18,fontWeight:"bold"}}>🪙 {coins.toLocaleString()}</div><div style={{fontSize:10}}>Coins</div></div><div style={{flex:1,background:"rgba(0,0,0,0.3)",borderRadius:12,padding:10,textAlign:"center"}}><div style={{fontSize:18,fontWeight:"bold"}}>🎁 12</div><div style={{fontSize:10}}>Gifts</div></div></div></div><div style={{padding:15}}><div style={{background:"#111",borderRadius:15,overflow:"hidden",border:"1px solid #222"}}><div style={{padding:"14px 15px",borderBottom:"1px solid #222",display:"flex",justifyContent:"space-between"}}><span>🎒 My Backpack</span><span>›</span></div><div style={{padding:"14px 15px",borderBottom:"1px solid #222",display:"flex",justifyContent:"space-between"}}><span>🏆 My Level</span><span>›</span></div><div style={{padding:"14px 15px",borderBottom:"1px solid #222",display:"flex",justifyContent:"space-between"}}><span>💰 My Earnings</span><span>›</span></div><div style={{padding:"14px 15px",borderBottom:"1px solid #222",display:"flex",justifyContent:"space-between"}}><span>⚙️ Settings</span><span>›</span></div><div style={{padding:"14px 15px",display:"flex",justifyContent:"space-between"}}><span>📞 Help Center</span><span>›</span></div></div><button onClick={logout} style={{width:"100%",marginTop:15,background:"#1a0000",color:"#ff4d4d",border:"1px solid #331111",padding:14,borderRadius:12,fontWeight:"bold"}}>🚪 Logout</button></div></div>}
    <div style={{position:"fixed",bottom:0,left:0,right:0,background:"#0a0a0a",borderTop:"1px solid #222",display:"flex",justifyContent:"space-around",padding:"8px 0"}}><button onClick={()=>setTab("home")} style={{background:"none",border:"none",color:tab==="home"?"#ff1493":"#666"}}>🏠<br/>Home</button><button onClick={()=>setTab("live")} style={{background:"none",border:"none",color:tab==="live"?"#ff1493":"#666"}}>📹<br/>Live</button><button onClick={()=>setTab("message")} style={{background:"none",border:"none",color:tab==="message"?"#ff1493":"#666"}}>💬<br/>Msg</button><button onClick={()=>setTab("profile")} style={{background:"none",border:"none",color:tab==="profile"?"#ff1493":"#666"}}>👤<br/>Profile</button></div>
  </div>);
}
